<?php

namespace  Business\AnnuaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{

   public function getLatestRegister($limit = null)
    { 
        $qb = $this->createQueryBuilder('a')
                   ->select('a')
                  ->addOrderBy('a.datepublication', 'DESC');
                  
                
        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
    public function Getlistannonce($souscategorie,$lieu,$motcle) {
        
        if($souscategorie!=null&&$lieu!='--Sélectionnez--'&&$motcle!=null)
        {
        $qb = $this->createQueryBuilder('a')
                   ->select('a')
                 ->where('a.souscategorie =:souscategorie and a.lieu LIKE :lieu and( a.titre LIKE :motcle or a.description LIKE :motcle)')
                 ->setParameters(array('motcle'=>'%'.$motcle.'%','lieu'=>'%'.$lieu.'%','souscategorie'=>$souscategorie));
        }
        else if($souscategorie==null&&$lieu!='--Sélectionnez--'&&$motcle!=null) {
       $qb = $this->createQueryBuilder('a')
                   ->select('a')
                 ->where('  a.lieu LIKE :lieu and( a.titre LIKE :motcle or a.description LIKE :motcle)')
                 ->setParameters(array('motcle'=>'%'.$motcle.'%','lieu'=>'%'.$lieu.'%'));
        
            
        }
        else if($souscategorie!=null&&$lieu=='--Sélectionnez--'&&$motcle!=null) {
         $qb = $this->createQueryBuilder('a')
                   ->select('a')
                 ->where('a.souscategorie =:souscategorie  and( a.titre LIKE :motcle or a.description LIKE :motcle)')
                 ->setParameters(array('motcle'=>'%'.$motcle.'%','souscategorie'=>$souscategorie));
       
            
        }
        else if($souscategorie!=null&&$lieu!='--Sélectionnez--'&&$motcle==null) {
        
            $qb = $this->createQueryBuilder('a')
                   ->select('a')
                 ->where('a.souscategorie =:souscategorie and a.lieu LIKE :lieu')
                 ->setParameters(array('lieu'=>'%'.$lieu.'%','souscategorie'=>$souscategorie));
       
        }
        else if($souscategorie==null&&$lieu!='--Sélectionnez--'&&$motcle==null) {
        
            $qb = $this->createQueryBuilder('a')
                   ->select('a')
                 ->where('a.lieu LIKE :lieu ')
                 ->setParameters(array('lieu'=>'%'.$lieu.'%'));
       
        }
        else if($souscategorie!=null&&$lieu=='--Sélectionnez--'&&$motcle==null) {
        $qb = $this->createQueryBuilder('a')
                   ->select('a')
                 ->where('a.souscategorie =:souscategorie ')
                 ->setParameters(array('souscategorie'=>$souscategorie));
       
            
        }
        else if($souscategorie==null&&$lieu=='--Sélectionnez--'&&$motcle!=null) {
        
            $qb = $this->createQueryBuilder('a')
                   ->select('a')
                 ->where(' a.titre LIKE :motcle or a.description LIKE :motcle')
                 ->setParameters(array('motcle'=>'%'.$motcle.'%'));
       
        }
        
        return $qb->getQuery()
                  ->getResult();
                 
    }
}
