<?php

namespace Business\AnnuaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
     public function getLatestRegister($limit = null)
    { 
        $qb = $this->createQueryBuilder('p')
                   ->select('p')
                  ->addOrderBy('p.datepublication', 'DESC');
                  
                
        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
}
