<?php

namespace  Business\AnnuaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepPromotionRepository extends EntityRepository
{

   public function getLatestReponses($user,$limit = null)
    { 
        $qb = $this->createQueryBuilder('a')
                   ->select('a')
                  ->where('a.promoteur=:user')
                  ->addOrderBy('a.datepublication', 'DESC')
                  ->setParameter('user', $user);
                
        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
   
}
