<?php

namespace  Business\AnnuaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getLatestRegister($limit = null)
    { 
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.typecompte=:type')
                  ->addOrderBy('c.dateinscription', 'DESC')
                  ->setParameter('type','Pro');
                
        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
public function getCompanyBy($motcle,$local) {
    
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                
                  ->Join('c.specialite','s')
                  ->where(' (s.nom LIKE :motcle or c.description LIKE :motcle) and (c.ville LIKE :local or c.adresse LIKE :local) and c.typecompte=:type')
                 ->setParameters(array('motcle'=>'%'.$motcle.'%','local'=>'%'.$local.'%','type'=>'Pro'));
        
        return $qb->getQuery()
                  ->getResult();
    
}
public function getCompanyByLocal($local) {
  $qb = $this->createQueryBuilder('c')
                   ->select('c')
                  ->where(' (c.ville LIKE :local or c.adresse LIKE :local) and c.typecompte=:type')
                 ->setParameters(array('local'=>'%'.$local.'%','type'=>'Pro'));
        
        return $qb->getQuery()
                  ->getResult();   
    
}
public function getCompanyByCle($motcle) {

     $qb = $this->createQueryBuilder('c')
                   ->select('c')
                
                  ->Join('c.specialite','s')
                  ->where(' (s.nom LIKE :motcle or c.description LIKE :motcle) and c.typecompte=:type ')
                 ->setParameters(array('motcle'=>'%'.$motcle.'%','type'=>'Pro'));
        
        return $qb->getQuery()
                  ->getResult();
}
    
}