<?php

namespace Proxies\__CG__\Business\AnnuaireBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Annonce extends \Business\AnnuaireBundle\Entity\Annonce implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'dureevalidite', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'lieu', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'prix', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'path', 'file', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'annonceur', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'datepublication', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'updated', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'souscategorie', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'reponses');
        }

        return array('__isInitialized__', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'dureevalidite', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'lieu', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'prix', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'path', 'file', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'annonceur', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'datepublication', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'updated', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'souscategorie', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Annonce' . "\0" . 'reponses');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Annonce $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', array());

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureevalidite($dureevalidite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureevalidite', array($dureevalidite));

        return parent::setDureevalidite($dureevalidite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureevalidite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureevalidite', array());

        return parent::getDureevalidite();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu($lieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', array($lieu));

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', array());

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', array($prix));

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', array());

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', array($path));

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', array());

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatepublication($datepublication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatepublication', array($datepublication));

        return parent::setDatepublication($datepublication);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatepublication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatepublication', array());

        return parent::getDatepublication();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnonceur(\Business\AnnuaireBundle\Entity\User $annonceur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnonceur', array($annonceur));

        return parent::setAnnonceur($annonceur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnonceur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnonceur', array());

        return parent::getAnnonceur();
    }

    /**
     * {@inheritDoc}
     */
    public function setSouscategorie(\Business\AnnuaireBundle\Entity\SousCategorie $souscategorie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSouscategorie', array($souscategorie));

        return parent::setSouscategorie($souscategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getSouscategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSouscategorie', array());

        return parent::getSouscategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function addReponse(\Business\AnnuaireBundle\Entity\RepAnnonce $reponses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReponse', array($reponses));

        return parent::addReponse($reponses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReponse(\Business\AnnuaireBundle\Entity\RepAnnonce $reponses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReponse', array($reponses));

        return parent::removeReponse($reponses);
    }

    /**
     * {@inheritDoc}
     */
    public function getReponses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReponses', array());

        return parent::getReponses();
    }

}
