<?php

namespace Proxies\__CG__\Business\AnnuaireBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Promotion extends \Business\AnnuaireBundle\Entity\Promotion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'id', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'nom', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'prenom', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'titre', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'telephone', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'description', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'path', 'file', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'promoteur', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'datepublication', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'reponses');
        }

        return array('__isInitialized__', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'id', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'nom', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'prenom', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'titre', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'telephone', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'description', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'path', 'file', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'promoteur', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'datepublication', '' . "\0" . 'Business\\AnnuaireBundle\\Entity\\Promotion' . "\0" . 'reponses');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Promotion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', array($path));

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', array());

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatepublication($datepublication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatepublication', array($datepublication));

        return parent::setDatepublication($datepublication);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatepublication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatepublication', array());

        return parent::getDatepublication();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromoteur(\Business\AnnuaireBundle\Entity\User $promoteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromoteur', array($promoteur));

        return parent::setPromoteur($promoteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoteur', array());

        return parent::getPromoteur();
    }

    /**
     * {@inheritDoc}
     */
    public function addReponse(\Business\AnnuaireBundle\Entity\RepPromotion $reponses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReponse', array($reponses));

        return parent::addReponse($reponses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReponse(\Business\AnnuaireBundle\Entity\RepPromotion $reponses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReponse', array($reponses));

        return parent::removeReponse($reponses);
    }

    /**
     * {@inheritDoc}
     */
    public function getReponses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReponses', array());

        return parent::getReponses();
    }

}
